name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Edit package.json
        run: npx json -I -f package.json -e 'this.homepage="${{ secrets.HOMEPAGE_URL }}"'

      - name: Install and Build
        run: |
          npm install
          npm run build
        env:
          REACT_APP_FALLBACK_CHAIN_ID: ${{ secrets.FALLBACK_CHAIN_ID }}
          REACT_APP_SUPPORTED_CHAIN_IDS: ${{ secrets.SUPPORTED_CHAIN_IDS }}
          REACT_APP_METAFACTORY_ADDRESSES: ${{ secrets.METAFACTORY_ADDRESSES }}
          REACT_APP_DAOFACTORY_ADDRESSES: ${{ secrets.DAOFACTORY_ADDRESSES }}
          REACT_APP_TREASURYMODULEFACTORY_ADDRESSES: ${{ secrets.TREASURYMODULEFACTORY_ADDRESSES }}
          REACT_APP_TOKENFACTORY_ADDRESSES: ${{ secrets.TOKENFACTORY_ADDRESSES }}
          REACT_APP_GOVERNORFACTORY_ADDRESSES: ${{ secrets.GOVERNORFACTORY_ADDRESSES }}
          REACT_APP_DAO_ADDRESSES: ${{ secrets.DAO_ADDRESSES }}
          REACT_APP_ACCESSCONTROL_ADDRESSES: ${{ secrets.ACCESSCONTROL_ADDRESSES }}
          REACT_APP_TREASURYMODULE_ADDRESSES: ${{ secrets.TREASURYMODULE_ADDRESSES }}
          REACT_APP_GOVERNORMODULE_ADDRESSES: ${{ secrets.GOVERNORMODULE_ADDRESSES }}
          REACT_APP_TIMELOCKUPGRADEABLE_ADDRESSES: ${{ secrets.TIMELOCKUPGRADEABLE_ADDRESSES }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: build
