name: Release IPFS Dev
on:
  push:
    branches:
      - develop

jobs:
  create_release:
    name: Create IPFS Release

    runs-on: ubuntu-latest

    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Install and Build
        run: |
          npm install
          npm run build
        env:
          REACT_APP_FALLBACK_CHAIN_ID: ${{ secrets.REACT_APP_FALLBACK_CHAIN_ID }}
          REACT_APP_SUPPORTED_CHAIN_IDS: ${{ secrets.REACT_APP_SUPPORTED_CHAIN_IDS }}
          REACT_APP_INFURA_API_KEY: ${{ secrets.REACT_APP_INFURA_API_KEY }}
          REACT_APP_ALCHEMY_API_KEY: ${{ secrets.REACT_APP_ALCHEMY_API_KEY }}
          REACT_APP_ETHERSCAN_API_KEY: ${{ secrets.REACT_APP_ETHERSCAN_API_KEY }}
          REACT_APP_METAFACTORY_ADDRESSES: ${{ secrets.REACT_APP_METAFACTORY_ADDRESSES }}
          REACT_APP_DAOFACTORY_ADDRESSES: ${{ secrets.REACT_APP_DAOFACTORY_ADDRESSES }}
          REACT_APP_TREASURYMODULEFACTORY_ADDRESSES: ${{ secrets.REACT_APP_TREASURYMODULEFACTORY_ADDRESSES }}
          REACT_APP_TOKENFACTORY_ADDRESSES: ${{ secrets.REACT_APP_TOKENFACTORY_ADDRESSES }}
          REACT_APP_GOVERNORFACTORY_ADDRESSES: ${{ secrets.REACT_APP_GOVERNORFACTORY_ADDRESSES }}
          REACT_APP_DAO_ADDRESSES: ${{ secrets.REACT_APP_DAO_ADDRESSES }}
          REACT_APP_ACCESSCONTROL_ADDRESSES: ${{ secrets.REACT_APP_ACCESSCONTROL_ADDRESSES }}
          REACT_APP_TREASURYMODULE_ADDRESSES: ${{ secrets.REACT_APP_TREASURYMODULE_ADDRESSES }}
          REACT_APP_GOVERNORMODULE_ADDRESSES: ${{ secrets.REACT_APP_GOVERNORMODULE_ADDRESSES }}
          REACT_APP_TIMELOCKUPGRADEABLE_ADDRESSES: ${{ secrets.REACT_APP_TIMELOCKUPGRADEABLE_ADDRESSES }}
          REACT_APP_SITE_URL: ${{ secrets.REACT_APP_SITE_URL }}

      - name: IPFS Pinata deploy GitHub action
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.3
        id: upload
        with:
          pin-name: ${{ secrets.PINATA_PIN_NAME }}
          path: './build'
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_API_SECRET_KEY }}

      - name: Convert CIDv0 to CIDv1
        id: convert_cidv0
        uses: uniswap/convert-cidv0-cidv1@v1.0.0
        with:
          cidv0: ${{ steps.upload.outputs.hash }}

      - name: Update DNS with new IPFS hash
        uses: textileio/cloudflare-update-dnslink@v2
        with:
          cid: ${{ steps.convert_cidv0.outputs.cidv1 }}
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          RECORD_DOMAIN: ${{ secrets.CLOUDFLARE_DOMAIN_NAME }}
          RECORD_NAME: ${{ secrets.CLOUDFLARE_RECORD_NAME }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
